// GENERATED by `npm run gen` from packages/schema/{constants,schema}.json.
// DO NOT EDIT BY HAND. Edit the JSON sources and re-run codegen.


export const RATING_KEYS = [
  "transport",
  "rent",
  "daily_essentials",
  "safety",
  "food",
  "green",
  "gym_sports",
  "vibe",
  "nightlife",
  "crowd"
] as const;

// Old pre-reorder key order. Used only to decode legacy shared URLs
// (9- or 10-position weight vectors in the OLD order). Never reorder,
// never delete — old links keep circulating.
export const LEGACY_WEIGHT_KEYS = [
  "food",
  "nightlife",
  "transport",
  "rent",
  "safety",
  "green",
  "gym_sports",
  "vibe",
  "crowd",
  "daily_essentials"
] as const;

// Order matches RATING_KEYS — do not reorder (positional URL decode depends on it).
export const DEFAULT_WEIGHTS: Record<string, number> = {
  "transport": 18,
  "rent": 18,
  "daily_essentials": 14,
  "safety": 10,
  "food": 12,
  "green": 8,
  "gym_sports": 4,
  "vibe": 4,
  "nightlife": 8,
  "crowd": 4
};

export interface FilterDefaults {
  minRent: number;
  maxRent: number;
  minCommute: number;
  maxCommute: number;
  categoryMins: Record<string, number>;
  hasLiveCamera: boolean;
}

export const DEFAULT_FILTERS: FilterDefaults = {
  minRent: 80000,
  maxRent: 300000,
  minCommute: 10,
  maxCommute: 60,
  categoryMins: {},
  hasLiveCamera: false,
};

export interface EnvironmentFilterDefaults {
  hideFloodRisk: boolean;
  hideHighSeismic: boolean;
}

export const DEFAULT_ENVIRONMENT_FILTERS: EnvironmentFilterDefaults = {
  hideFloodRisk: false,
  hideHighSeismic: false,
};

export const RENT_FLOOR = 80000;
export const RENT_CEILING = 300000;

// Order matches RATING_KEYS — do not reorder.
export const RATING_LABELS_EN: Record<string, string> = {
  "transport": "Transport",
  "rent": "Affordability",
  "daily_essentials": "Daily Essentials",
  "safety": "Safety",
  "food": "Food & Dining",
  "green": "Parks & Green",
  "gym_sports": "Gym & Sports",
  "vibe": "Vibe & Atmosphere",
  "nightlife": "Nightlife",
  "crowd": "Quietness"
};

export const COMPOSITE_ANCHORS_DEFAULT = {
  p5: 3.6,
  p50: 6,
  p95: 7.15,
};

export const PERCENTILE_ANCHORS_EMPTY_FALLBACK = {
  p5: 1,
  p50: 5.5,
  p95: 10,
};

/** Constants used only by the offline rating pipeline (compute-ratings.py).
 *  Not imported by the app or MCP server. Kept here so it lives in the
 *  single source of truth alongside everything else. */
export const PIPELINE_ONLY = {
  absoluteCaps: {
  "food": [
    [
      8,
      100
    ],
    [
      9,
      400
    ],
    [
      10,
      1000
    ]
  ],
  "nightlife": [
    [
      8,
      20
    ],
    [
      9,
      100
    ],
    [
      10,
      300
    ]
  ],
  "transport": [
    [
      8,
      2
    ],
    [
      9,
      3
    ],
    [
      10,
      5
    ]
  ],
  "green": [
    [
      8,
      25
    ],
    [
      9,
      50
    ],
    [
      10,
      80
    ]
  ],
  "gym_sports": [
    [
      8,
      7
    ],
    [
      9,
      12
    ],
    [
      10,
      20
    ]
  ],
  "vibe": [
    [
      8,
      8
    ],
    [
      9,
      20
    ],
    [
      10,
      50
    ]
  ],
  "rent": [
    [
      9,
      1
    ],
    [
      10,
      2
    ]
  ]
},
  tokyoStationLat: 35.6812,
  tokyoStationLng: 139.7671,
} as const;
