// GENERATED by `npm run gen` from packages/schema/{constants,schema}.json.
// DO NOT EDIT BY HAND. Edit the JSON sources and re-run codegen.


/**
 * Canonical rating dimension. Order is defined in constants.json rating_keys and is load-bearing.
 */
export type RatingKey = 'transport' | 'rent' | 'daily_essentials' | 'safety' | 'food' | 'green' | 'gym_sports' | 'vibe' | 'nightlife' | 'crowd';

export type ConfidenceLevel = 'strong' | 'moderate' | 'estimate' | 'editorial';

export type SeismicRiskTier = 'low' | 'moderate' | 'high' | 'very_high' | 'unknown';

export type ElevationTier = 'very_low' | 'low' | 'moderate' | 'elevated' | 'high' | 'mountain' | 'unknown';

/**
 * The 10 canonical rating dimensions. All required.
 */
export interface StationRatings {
  transport: number;
  rent: number;
  dailyEssentials: number;
  safety: number;
  food: number;
  green: number;
  gymSports: number;
  vibe: number;
  nightlife: number;
  crowd: number;
}

/**
 * Per-dimension weights. Same shape as station_ratings.
 */
export interface WeightConfig {
  transport: number;
  rent: number;
  dailyEssentials: number;
  safety: number;
  food: number;
  green: number;
  gymSports: number;
  vibe: number;
  nightlife: number;
  crowd: number;
}

/**
 * Per-dimension confidence. daily_essentials is optional (pipeline has not yet regenerated all entries).
 */
export interface StationConfidence {
  food: ConfidenceLevel;
  nightlife: ConfidenceLevel;
  transport: ConfidenceLevel;
  rent: ConfidenceLevel;
  safety: ConfidenceLevel;
  green: ConfidenceLevel;
  gymSports: ConfidenceLevel;
  vibe: ConfidenceLevel;
  crowd: ConfidenceLevel;
  dailyEssentials?: ConfidenceLevel;
}

/**
 * Per-dimension source URLs. daily_essentials optional (same reason as station_confidence).
 */
export interface StationSources {
  food: Array<string>;
  nightlife: Array<string>;
  transport: Array<string>;
  rent: Array<string>;
  safety: Array<string>;
  green: Array<string>;
  gymSports: Array<string>;
  vibe: Array<string>;
  crowd: Array<string>;
  dailyEssentials?: Array<string>;
}

/**
 * Rent averages. NOTE: the '1k_1ldk' key starts with a digit — it is a valid JSON object key but requires quoting in TS and aliasing in Pydantic.
 */
export interface RentAvg {
  '1k_1ldk': number | null;
  '2ldk': number | null;
  source: string;
  updated: string;
}

/**
 * Minutes to the five major hubs.
 */
export interface TransitMinutes {
  shibuya: number;
  shinjuku: number;
  tokyo: number;
  ikebukuro: number;
  shinagawa: number;
}

/**
 * All fields optional — populated by the environment pipeline.
 */
export interface EnvironmentData {
  elevationM?: number;
  elevationTier?: ElevationTier;
  seismicProbI60?: number;
  seismicProbI55?: number;
  seismicRiskTier?: SeismicRiskTier;
}

/**
 * User-facing filter state. NOTE: does NOT include environment filters (hide_flood_risk / hide_high_seismic) — those live in environment_filters because they are toggleable separately from the main filter panel.
 */
export interface FilterState {
  minRent: number;
  maxRent: number;
  minCommute: number;
  maxCommute: number;
  categoryMins: Record<RatingKey, number>;
  hasLiveCamera: boolean;
}

/**
 * Environment safety toggles, separate from filter_state.
 */
export interface EnvironmentFilters {
  hideFloodRisk: boolean;
  hideHighSeismic: boolean;
}

/**
 * p5 / p50 / p95 anchors for the diverging composite palette.
 */
export interface PercentileAnchors {
  p5: number;
  p50: number;
  p95: number;
}

/**
 * Named preset profile (Young Pro / Family / etc).
 */
export interface PresetProfile {
  id: string;
  label: string;
  icon: string;
  weights: WeightConfig;
  filters?: {
    minRent?: number;
    maxRent?: number;
    minCommute?: number;
    maxCommute?: number;
    categoryMins?: Record<RatingKey, number>;
    hasLiveCamera?: boolean;
  };
}
