"""GENERATED by `npm run gen` from packages/schema/{constants,schema}.json.
DO NOT EDIT BY HAND. Edit the JSON sources and re-run codegen."""

from types import SimpleNamespace

# 10 rating dimensions, life-first order. DO NOT REORDER —
# positional URL decode depends on this order.
RATING_KEYS: tuple[str, ...] = (
    "transport",
    "rent",
    "daily_essentials",
    "safety",
    "food",
    "green",
    "gym_sports",
    "vibe",
    "nightlife",
    "crowd",
)


# Old pre-reorder key order. Backcompat only — used to decode legacy shared URLs.
# Never delete; old links keep circulating.
LEGACY_WEIGHT_KEYS: tuple[str, ...] = (
    "food",
    "nightlife",
    "transport",
    "rent",
    "safety",
    "green",
    "gym_sports",
    "vibe",
    "crowd",
    "daily_essentials",
)


# Order matches RATING_KEYS — do not reorder.
DEFAULT_WEIGHTS: dict[str, int] = {
    "transport": 18,
    "rent": 18,
    "daily_essentials": 14,
    "safety": 10,
    "food": 12,
    "green": 8,
    "gym_sports": 4,
    "vibe": 4,
    "nightlife": 8,
    "crowd": 4,
}


DEFAULT_FILTERS: dict = {
    "min_rent": 80000,
    "max_rent": 300000,
    "min_commute": 10,
    "max_commute": 60,
    "category_mins": {},
    "has_live_camera": False,
}


DEFAULT_ENVIRONMENT_FILTERS: dict = {
    "hide_flood_risk": False,
    "hide_high_seismic": False,
}


RENT_FLOOR = 80000
RENT_CEILING = 300000

# Order matches RATING_KEYS — do not reorder.
RATING_LABELS_EN: dict[str, str] = {
    "transport": "Transport",
    "rent": "Affordability",
    "daily_essentials": "Daily Essentials",
    "safety": "Safety",
    "food": "Food & Dining",
    "green": "Parks & Green",
    "gym_sports": "Gym & Sports",
    "vibe": "Vibe & Atmosphere",
    "nightlife": "Nightlife",
    "crowd": "Quietness",
}


COMPOSITE_ANCHORS_DEFAULT: dict[str, float] = {
    "p5": 3.6,
    "p50": 6,
    "p95": 7.15,
}

PERCENTILE_ANCHORS_EMPTY_FALLBACK: dict[str, float] = {
    "p5": 1,
    "p50": 5.5,
    "p95": 10,
}

# Constants used only by the offline rating pipeline (compute-ratings.py).
# Format for absolute_caps: dict[category] -> list[(min_rating, threshold)] tuples.
# Not imported by the app or MCP server.
PIPELINE_ONLY = SimpleNamespace(
    absolute_caps={
        "food": [(8, 100), (9, 400), (10, 1000)],
        "nightlife": [(8, 20), (9, 100), (10, 300)],
        "transport": [(8, 2), (9, 3), (10, 5)],
        "green": [(8, 25), (9, 50), (10, 80)],
        "gym_sports": [(8, 7), (9, 12), (10, 20)],
        "vibe": [(8, 8), (9, 20), (10, 50)],
        "rent": [(9, 1), (10, 2)],
    },
    tokyo_station_lat=35.6812,
    tokyo_station_lng=139.7671,
)
