"""GENERATED by `npm run gen` from packages/schema/{constants,schema}.json.
DO NOT EDIT BY HAND. Edit the JSON sources and re-run codegen."""

from __future__ import annotations

from typing import Literal, Optional

from pydantic import BaseModel, ConfigDict, Field

RatingKey = Literal["transport", "rent", "daily_essentials", "safety", "food", "green", "gym_sports", "vibe", "nightlife", "crowd"]
ConfidenceLevel = Literal["strong", "moderate", "estimate", "editorial"]
SeismicRiskTier = Literal["low", "moderate", "high", "very_high", "unknown"]
ElevationTier = Literal["very_low", "low", "moderate", "elevated", "high", "mountain", "unknown"]

class StationRatings(BaseModel):
    """
    The 10 canonical rating dimensions. All required.
    """

    transport: float = Field(...)
    rent: float = Field(...)
    daily_essentials: float = Field(...)
    safety: float = Field(...)
    food: float = Field(...)
    green: float = Field(...)
    gym_sports: float = Field(...)
    vibe: float = Field(...)
    nightlife: float = Field(...)
    crowd: float = Field(...)

class WeightConfig(BaseModel):
    """
    Per-dimension weights. Same shape as station_ratings.
    """

    transport: float = Field(...)
    rent: float = Field(...)
    daily_essentials: float = Field(...)
    safety: float = Field(...)
    food: float = Field(...)
    green: float = Field(...)
    gym_sports: float = Field(...)
    vibe: float = Field(...)
    nightlife: float = Field(...)
    crowd: float = Field(...)

class StationConfidence(BaseModel):
    """
    Per-dimension confidence. daily_essentials is optional (pipeline has not yet regenerated all entries).
    """

    food: ConfidenceLevel = Field(...)
    nightlife: ConfidenceLevel = Field(...)
    transport: ConfidenceLevel = Field(...)
    rent: ConfidenceLevel = Field(...)
    safety: ConfidenceLevel = Field(...)
    green: ConfidenceLevel = Field(...)
    gym_sports: ConfidenceLevel = Field(...)
    vibe: ConfidenceLevel = Field(...)
    crowd: ConfidenceLevel = Field(...)
    daily_essentials: Optional[ConfidenceLevel] = None

class StationSources(BaseModel):
    """
    Per-dimension source URLs. daily_essentials optional (same reason as station_confidence).
    """

    food: list[str] = Field(...)
    nightlife: list[str] = Field(...)
    transport: list[str] = Field(...)
    rent: list[str] = Field(...)
    safety: list[str] = Field(...)
    green: list[str] = Field(...)
    gym_sports: list[str] = Field(...)
    vibe: list[str] = Field(...)
    crowd: list[str] = Field(...)
    daily_essentials: Optional[list[str]] = None

class RentAvg(BaseModel):
    """
    Rent averages. NOTE: the '1k_1ldk' key starts with a digit — it is a valid JSON object key but requires quoting in TS and aliasing in Pydantic.
    """

    model_config = ConfigDict(populate_by_name=True)

    one_k_1ldk: float | None = Field(..., alias="1k_1ldk")
    one_ldk: float | None = Field(..., alias="2ldk")
    source: str = Field(...)
    updated: str = Field(...)

class TransitMinutes(BaseModel):
    """
    Minutes to the five major hubs.
    """

    shibuya: float = Field(...)
    shinjuku: float = Field(...)
    tokyo: float = Field(...)
    ikebukuro: float = Field(...)
    shinagawa: float = Field(...)

class EnvironmentData(BaseModel):
    """
    All fields optional — populated by the environment pipeline.
    """

    elevation_m: Optional[float] = None
    elevation_tier: Optional[ElevationTier] = None
    seismic_prob_i60: Optional[float] = None
    seismic_prob_i55: Optional[float] = None
    seismic_risk_tier: Optional[SeismicRiskTier] = None

class FilterState(BaseModel):
    """
    User-facing filter state. NOTE: does NOT include environment filters (hide_flood_risk / hide_high_seismic) — those live in environment_filters because they are toggleable separately from the main filter panel.
    """

    min_rent: float = Field(...)
    max_rent: float = Field(...)
    min_commute: float = Field(...)
    max_commute: float = Field(...)
    category_mins: dict[str, float] = Field(...)
    has_live_camera: bool = Field(...)

class EnvironmentFilters(BaseModel):
    """
    Environment safety toggles, separate from filter_state.
    """

    hide_flood_risk: bool = Field(...)
    hide_high_seismic: bool = Field(...)

class PercentileAnchors(BaseModel):
    """
    p5 / p50 / p95 anchors for the diverging composite palette.
    """

    p5: float = Field(...)
    p50: float = Field(...)
    p95: float = Field(...)

class PresetProfile(BaseModel):
    """
    Named preset profile (Young Pro / Family / etc).
    """

    id: str = Field(...)
    label: str = Field(...)
    icon: str = Field(...)
    weights: WeightConfig = Field(...)
    filters: Optional[dict] = None
