import districtsData from '@/data/bangkok/districts.json';
import railData from '@/data/bangkok/rail.json';
import stationAreasData from '@/data/bangkok/stations.json';
import type { District, MapStation, RailLine, RailStation, StationArea } from './types';
import type { Locale } from '@/i18n/routing';
import { stationAreaKey } from './area-key';

/**
 * Bangkok district data (generated by scripts/bangkok/build.py).
 *
 * Server-side accessors — the homepage passes the lightweight `MapStation`
 * shape to client components, exactly like Tokyo's `getMapStations()`.
 * Geometry and the rail overlay are NOT here: the district map imports those
 * JSON files itself, so they ship in its lazy chunk instead of every page's
 * RSC payload.
 */

export type RailLineWithPaths = RailLine & { paths: [number, number][][] };

const districts = (districtsData as unknown as { districts: District[] }).districts;
const districtBySlug = new Map(districts.map((d) => [d.slug, d]));
const rail = railData as unknown as { lines: RailLineWithPaths[]; stations: RailStation[] };
const stationById = new Map(rail.stations.map((s) => [s.id, s]));
const lineById = new Map(rail.lines.map((l) => [l.id, l]));
const areas = (stationAreasData as unknown as { areas: StationArea[] }).areas;
const areaById = new Map(areas.map((a) => [a.id, a]));

export function getBangkokDistricts(): District[] {
  return districts;
}

export function getBangkokDistrict(slug: string): District | undefined {
  return districtBySlug.get(slug);
}

export function getBangkokSlugs(): string[] {
  return districts.map((d) => d.slug);
}

export function getRailStation(id: string): RailStation | undefined {
  return stationById.get(id);
}

export function getRailLine(id: string): RailLineWithPaths | undefined {
  return lineById.get(id);
}

/** Search terms for a district: curated neighbourhood names + its stations. */
function searchAliases(d: District): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const term of [...d.aliases, ...d.station_ids.map((id) => stationById.get(id)?.name_en ?? '')]) {
    const key = term.toLowerCase();
    if (term && !seen.has(key) && key !== d.name_en.toLowerCase()) {
      seen.add(key);
      out.push(term);
    }
  }
  return out;
}

let mapCache: MapStation[] | null = null;

/** Lightweight district list for the homepage map, filter panel and search. */
export function getBangkokMapDistricts(): MapStation[] {
  if (mapCache) return mapCache;
  mapCache = districts.map((d) => ({
    slug: d.slug,
    name_en: d.name_en,
    name_jp: d.name_jp,
    name_ru: d.name_ru,
    name_th: d.name_th,
    lat: d.lat,
    lng: d.lng,
    line_count: d.line_ids.length,
    station_count: d.station_ids.length,
    aliases: searchAliases(d),
    ratings: d.ratings,
    rent_1k: d.rent.one_bed,
    min_transit: d.min_transit,
    elevation_m: null,
    seismic_risk_tier: null,
  }));
  return mapCache;
}

/** Hero image per district for tooltips / popups (Commons, no LQIP). */
export function getBangkokThumbnails(): Record<string, { thumb: string; lqip: string }> {
  const out: Record<string, { thumb: string; lqip: string }> = {};
  for (const d of districts) {
    if (d.image) out[d.slug] = { thumb: d.image.thumb, lqip: '' };
  }
  return out;
}

/** One-paragraph atmosphere snippet per district for the selected locale. */
export function getBangkokSnippets(locale: Locale): Record<string, string> {
  const out: Record<string, string> = {};
  for (const d of districts) {
    const atmo = d.description?.[locale]?.atmosphere;
    if (atmo) out[d.slug] = atmo.length > 140 ? `${atmo.slice(0, 140).trimEnd()}…` : atmo;
  }
  return out;
}

// ─── Station areas (the level between districts and the 200 m grid) ────────

export function getBangkokStationAreas(): StationArea[] {
  return areas;
}

export function getBangkokStationArea(id: string): StationArea | undefined {
  return areaById.get(id);
}

export function getBangkokStationAreaIds(): string[] {
  return areas.map((a) => a.id);
}

let areaMapCache: MapStation[] | null = null;

/**
 * Station areas in the homepage `MapStation` shape. `slug` is the typed key
 * (`st.<id>`, see lib/area-key.ts) so districts and station areas can share
 * the one selection / hover / compare slot of the Bangkok store slice.
 */
export function getBangkokMapStationAreas(): MapStation[] {
  if (areaMapCache) return areaMapCache;
  areaMapCache = areas.map((a) => ({
    slug: stationAreaKey(a.id),
    name_en: a.name_en,
    name_jp: a.name_jp,
    name_th: a.name_th,
    lat: a.lat,
    lng: a.lng,
    line_count: a.line_ids.length,
    station_count: a.station_ids.length,
    line_ids: a.line_ids,
    line_colors: a.line_ids.map((id) => lineById.get(id)?.color ?? '#6b7280'),
    district: a.district,
    ratings: a.ratings,
    rent_1k: a.rent.one_bed,
    min_transit: a.min_transit,
    elevation_m: null,
    seismic_risk_tier: null,
  }));
  return areaMapCache;
}

/** Commons photo per station area (Wikidata P18 of its station), keyed like the map. */
export function getBangkokStationAreaThumbnails(): Record<string, { thumb: string; lqip: string }> {
  const out: Record<string, { thumb: string; lqip: string }> = {};
  for (const a of areas) {
    if (a.image) out[stationAreaKey(a.id)] = { thumb: a.image.thumb, lqip: '' };
  }
  return out;
}
