import districtsData from '@/data/bangkok/districts.json';
import railData from '@/data/bangkok/rail.json';
import type { District, MapStation, RailLine, RailStation } from './types';
import type { Locale } from '@/i18n/routing';

/**
 * Bangkok district data (generated by scripts/bangkok/build.py).
 *
 * Server-side accessors — the homepage passes the lightweight `MapStation`
 * shape to client components, exactly like Tokyo's `getMapStations()`.
 * Geometry and the rail overlay are NOT here: the district map imports those
 * JSON files itself, so they ship in its lazy chunk instead of every page's
 * RSC payload.
 */

export type RailLineWithPaths = RailLine & { paths: [number, number][][] };

const districts = (districtsData as unknown as { districts: District[] }).districts;
const districtBySlug = new Map(districts.map((d) => [d.slug, d]));
const rail = railData as unknown as { lines: RailLineWithPaths[]; stations: RailStation[] };
const stationById = new Map(rail.stations.map((s) => [s.id, s]));
const lineById = new Map(rail.lines.map((l) => [l.id, l]));

export function getBangkokDistricts(): District[] {
  return districts;
}

export function getBangkokDistrict(slug: string): District | undefined {
  return districtBySlug.get(slug);
}

export function getBangkokSlugs(): string[] {
  return districts.map((d) => d.slug);
}

export function getRailStation(id: string): RailStation | undefined {
  return stationById.get(id);
}

export function getRailLine(id: string): RailLineWithPaths | undefined {
  return lineById.get(id);
}

/** Search terms for a district: curated neighbourhood names + its stations. */
function searchAliases(d: District): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const term of [...d.aliases, ...d.station_ids.map((id) => stationById.get(id)?.name_en ?? '')]) {
    const key = term.toLowerCase();
    if (term && !seen.has(key) && key !== d.name_en.toLowerCase()) {
      seen.add(key);
      out.push(term);
    }
  }
  return out;
}

let mapCache: MapStation[] | null = null;

/** Lightweight district list for the homepage map, filter panel and search. */
export function getBangkokMapDistricts(): MapStation[] {
  if (mapCache) return mapCache;
  mapCache = districts.map((d) => ({
    slug: d.slug,
    name_en: d.name_en,
    name_jp: d.name_jp,
    name_ru: d.name_ru,
    name_th: d.name_th,
    lat: d.lat,
    lng: d.lng,
    line_count: d.line_ids.length,
    station_count: d.station_ids.length,
    aliases: searchAliases(d),
    ratings: d.ratings,
    rent_1k: d.rent.one_bed,
    min_transit: d.min_transit,
    elevation_m: null,
    seismic_risk_tier: null,
  }));
  return mapCache;
}

/** Hero image per district for tooltips / popups (Commons, no LQIP). */
export function getBangkokThumbnails(): Record<string, { thumb: string; lqip: string }> {
  const out: Record<string, { thumb: string; lqip: string }> = {};
  for (const d of districts) {
    if (d.image) out[d.slug] = { thumb: d.image.thumb, lqip: '' };
  }
  return out;
}

/** One-paragraph atmosphere snippet per district for the selected locale. */
export function getBangkokSnippets(locale: Locale): Record<string, string> {
  const out: Record<string, string> = {};
  for (const d of districts) {
    const atmo = d.description?.[locale]?.atmosphere;
    if (atmo) out[d.slug] = atmo.length > 140 ? `${atmo.slice(0, 140).trimEnd()}…` : atmo;
  }
  return out;
}
