#!/usr/bin/env tsx
/**
 * Codegen for @city-rating/schema.
 *
 * Reads constants.json + schema.json from this package's root and emits:
 *   - ts/constants.ts        (typed constants)
 *   - ts/types.ts            (TS interfaces matching schema.json $defs)
 *   - ts/index.ts            (re-exports)
 *   - python/city_rating_schema/constants.py
 *   - python/city_rating_schema/models.py      (Pydantic v2)
 *   - python/city_rating_schema/__init__.py
 *
 * The output MUST be byte-identical on re-run so CI can assert
 * `npm run gen && git diff --exit-code`. To stay deterministic:
 *   - never read system clock / Math.random / Date.now
 *   - never iterate a plain object's keys via spread or for..of when order
 *     matters — read the explicit ordered arrays from constants.json
 *   - always write files with a trailing newline and 2-space indent
 *
 * Run: `npm run gen` (or `npx tsx scripts/gen.ts`) from packages/schema.
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PKG_ROOT = resolve(__dirname, '..');

// ---------- helpers ----------

const HEADER_TS = `// GENERATED by \`npm run gen\` from packages/schema/{constants,schema}.json.
// DO NOT EDIT BY HAND. Edit the JSON sources and re-run codegen.
`;

const HEADER_PY = `\"\"\"GENERATED by \`npm run gen\` from packages/schema/{constants,schema}.json.
DO NOT EDIT BY HAND. Edit the JSON sources and re-run codegen.\"\"\"
`;

/** Write file, ensuring parent dir exists, with a trailing newline. */
function emit(path: string, content: string): void {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content.endsWith('\n') ? content : content + '\n');
}

/** Snake_case → camelCase (only for filter field names). */
function camel(s: string): string {
  return s.replace(/_([a-z])/g, (_, c) => c.toUpperCase());
}

/** Capitalize first letter (used to make TS type names from $ref keys). */
function pascal(s: string): string {
  // snake_case → PascalCase
  return s
    .split('_')
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join('');
}

/** JSON.stringify with 2-space indent. */
const j = (v: unknown) => JSON.stringify(v, null, 2);

// ---------- load sources ----------

const constants = JSON.parse(readFileSync(join(PKG_ROOT, 'constants.json'), 'utf8'));
const schema = JSON.parse(readFileSync(join(PKG_ROOT, 'schema.json'), 'utf8'));
const defs = schema.$defs as Record<string, any>;

// ---------- ts/constants.ts ----------

function emitTsConstants(): string {
  const lines: string[] = [HEADER_TS, ''];

  // RATING_KEYS — readonly array, exact order preserved
  lines.push(
    `export const RATING_KEYS = ${j(constants.rating_keys)} as const;`,
    '',
    '// Old pre-reorder key order. Used only to decode legacy shared URLs',
    '// (9- or 10-position weight vectors in the OLD order). Never reorder,',
    '// never delete — old links keep circulating.',
    `export const LEGACY_WEIGHT_KEYS = ${j(constants.legacy_weight_keys)} as const;`,
    '',
  );

  // DEFAULT_WEIGHTS — order matches RATING_KEYS
  lines.push(
    '// Order matches RATING_KEYS — do not reorder (positional URL decode depends on it).',
    `export const DEFAULT_WEIGHTS: Record<string, number> = ${j(constants.default_weights)};`,
    '',
  );

  // DEFAULT_FILTERS — camelCase
  const df = constants.default_filters;
  lines.push(
    'export interface FilterDefaults {',
    `  minRent: number;`,
    `  maxRent: number;`,
    `  minCommute: number;`,
    `  maxCommute: number;`,
    `  categoryMins: Record<string, number>;`,
    `  hasLiveCamera: boolean;`,
    `}`,
    '',
    'export const DEFAULT_FILTERS: FilterDefaults = {',
    `  minRent: ${df.min_rent},`,
    `  maxRent: ${df.max_rent},`,
    `  minCommute: ${df.min_commute},`,
    `  maxCommute: ${df.max_commute},`,
    `  categoryMins: ${j(df.category_mins)},`,
    `  hasLiveCamera: ${df.has_live_camera},`,
    `};`,
    '',
  );

  // DEFAULT_ENVIRONMENT_FILTERS — camelCase
  const de = constants.default_environment_filters;
  lines.push(
    'export interface EnvironmentFilterDefaults {',
    `  hideFloodRisk: boolean;`,
    `  hideHighSeismic: boolean;`,
    `}`,
    '',
    'export const DEFAULT_ENVIRONMENT_FILTERS: EnvironmentFilterDefaults = {',
    `  hideFloodRisk: ${de.hide_flood_risk},`,
    `  hideHighSeismic: ${de.hide_high_seismic},`,
    `};`,
    '',
  );

  // RENT_FLOOR / RENT_CEILING
  lines.push(
    `export const RENT_FLOOR = ${constants.rent_floor};`,
    `export const RENT_CEILING = ${constants.rent_ceiling};`,
    '',
  );

  // RATING_LABELS_EN — order matches RATING_KEYS
  lines.push(
    '// Order matches RATING_KEYS — do not reorder.',
    `export const RATING_LABELS_EN: Record<string, string> = ${j(constants.rating_labels_en)};`,
    '',
  );

  // COMPOSITE_ANCHORS_DEFAULT
  const cad = constants.composite_anchors_default;
  lines.push(
    'export const COMPOSITE_ANCHORS_DEFAULT = {',
    `  p5: ${cad.p5},`,
    `  p50: ${cad.p50},`,
    `  p95: ${cad.p95},`,
    `};`,
    '',
  );

  // PERCENTILE_ANCHORS_EMPTY_FALLBACK
  const paf = constants.percentile_anchors_empty_fallback;
  lines.push(
    'export const PERCENTILE_ANCHORS_EMPTY_FALLBACK = {',
    `  p5: ${paf.p5},`,
    `  p50: ${paf.p50},`,
    `  p95: ${paf.p95},`,
    `};`,
    '',
  );

  // PIPELINE_ONLY — passthrough as an opaque object, but typed minimally
  // (consumers are scripts/compute-ratings.py only; TS code does not use it).
  const po = constants.pipeline_only;
  lines.push(
    '/** Constants used only by the offline rating pipeline (compute-ratings.py).',
    ' *  Not imported by the app or MCP server. Kept here so it lives in the',
    ' *  single source of truth alongside everything else. */',
    'export const PIPELINE_ONLY = {',
    `  absoluteCaps: ${j(po.absolute_caps)},`,
    `  tokyoStationLat: ${po.tokyo_station_lat},`,
    `  tokyoStationLng: ${po.tokyo_station_lng},`,
    `} as const;`,
    '',
  );

  return lines.join('\n');
}

// ---------- ts/types.ts ----------

/** Render a TS-safe property name: quote digit-prefixed keys, camelCase snake_keys. */
function tsPropName(key: string): string {
  const camelCased = camel(key);
  if (/^[\d]/.test(camelCased)) return `'${camelCased}'`;
  return camelCased;
}

/** Convert a JSON Schema type to a TS type string. */
function tsType(node: any): string {
  if (typeof node !== 'object' || node === null) return 'unknown';
  if ('$ref' in node) {
    const refName = node.$ref.replace('#/$defs/', '');
    return pascal(refName);
  }
  if (node.enum) {
    return node.enum.map((v: string) => `'${v}'`).join(' | ');
  }
  if (node.type === 'number' || node.type === 'integer') return 'number';
  if (node.type === 'string') return 'string';
  if (node.type === 'boolean') return 'boolean';
  if (Array.isArray(node.type)) {
    // e.g. ["number","null"]
    return node.type
      .map((t: string) => (t === 'null' ? 'null' : tsType({ ...node, type: t })))
      .join(' | ');
  }
  if (node.type === 'array') {
    return `Array<${tsType(node.items)}>`;
  }
  if (node.type === 'object') {
    // Free-form map: {additionalProperties: {...}} with no listed `properties`.
    if ((!node.properties || Object.keys(node.properties).length === 0) && node.additionalProperties) {
      const valT = tsType(node.additionalProperties);
      // If propertyNames constrains keys to rating_key, narrow to RatingKey.
      const keyT = node.propertyNames && node.propertyNames.$ref ? 'RatingKey' : 'string';
      return `Record<${keyT}, ${valT}>`;
    }
    // Inline object with named properties. Indented for nesting inside an
    // interface body (4 spaces so it reads cleanly under a 2-space field).
    const props = node.properties || {};
    const required = new Set(node.required || []);
    const fields = Object.entries(props).map(([k, v]) => {
      const opt = required.has(k) ? '' : '?';
      return `    ${tsPropName(k)}${opt}: ${tsType(v as any)};`;
    });
    if (fields.length === 0) return 'Record<string, never>';
    return `{\n${fields.join('\n')}\n  }`;
  }
  return 'unknown';
}

/** Emit a TS interface from a $def that has type:object. */
function emitTsInterface(name: string, def: any): string {
  const props = def.properties || {};
  const required = new Set<string>(def.required || []);
  const lines: string[] = [];

  if (def.description) {
    lines.push('/**');
    for (const line of String(def.description).split('\n')) {
      lines.push(` * ${line}`);
    }
    lines.push(' */');
  }

  lines.push(`export interface ${pascal(name)} {`);
  for (const [key, val] of Object.entries(props)) {
    const isReq = required.has(key);
    const opt = isReq ? '' : '?';
    lines.push(`  ${tsPropName(key)}${opt}: ${tsType(val as any)};`);
  }
  lines.push('}');
  return lines.join('\n');
}

function emitTsTypes(): string {
  const lines: string[] = [HEADER_TS, ''];

  // 1. String-union enums first (rating_key, confidence_level, etc.)
  const enumDefs = Object.entries(defs).filter(([, d]) => d.enum);
  for (const [name, def] of enumDefs) {
    if (def.description) {
      lines.push('/**');
      for (const l of String(def.description).split('\n')) lines.push(` * ${l}`);
      lines.push(' */');
    }
    lines.push(`export type ${pascal(name)} = ${(def as any).enum.map((v: string) => `'${v}'`).join(' | ')};`, '');
  }

  // 2. Object interfaces in $def declaration order
  const objDefs = Object.entries(defs).filter(([, d]) => d.type === 'object');
  for (const [name, def] of objDefs) {
    lines.push(emitTsInterface(name, def), '');
  }

  return lines.join('\n');
}

// ---------- ts/index.ts ----------

function emitTsIndex(): string {
  return [
    HEADER_TS,
    "export * from './constants.js';",
    "export * from './types.js';",
    '',
  ].join('\n');
}

// ---------- python/city_rating_schema/constants.py ----------

function pyRepr(v: unknown): string {
  if (v === null || v === undefined) return 'None';
  if (typeof v === 'boolean') return v ? 'True' : 'False';
  if (typeof v === 'number') return String(v);
  if (typeof v === 'string') return JSON.stringify(v);
  if (Array.isArray(v)) {
    if (v.length === 0) return '()';
    const inner = v.map(pyRepr).join(', ');
    // tuple-of-tuples stays readable
    return `(\n    ${inner.replace(/, /g, ',\n    ')},\n)`; // not used for scalars
  }
  return JSON.stringify(v, null, 2);
}

function emitPythonConstants(): string {
  const lines: string[] = [HEADER_PY];

  // SimpleNamespace is needed for PIPELINE_ONLY below.
  lines.push('from types import SimpleNamespace', '');

  // RATING_KEYS — tuple
  lines.push(
    '# 10 rating dimensions, life-first order. DO NOT REORDER —',
    '# positional URL decode depends on this order.',
    `RATING_KEYS: tuple[str, ...] = (`,
  );
  for (const k of constants.rating_keys) lines.push(`    ${JSON.stringify(k)},`);
  lines.push(')', '', '');

  // LEGACY_WEIGHT_KEYS — tuple, backcompat
  lines.push(
    '# Old pre-reorder key order. Backcompat only — used to decode legacy shared URLs.',
    '# Never delete; old links keep circulating.',
    `LEGACY_WEIGHT_KEYS: tuple[str, ...] = (`,
  );
  for (const k of constants.legacy_weight_keys) lines.push(`    ${JSON.stringify(k)},`);
  lines.push(')', '', '');

  // DEFAULT_WEIGHTS — dict, order matches RATING_KEYS
  lines.push(
    '# Order matches RATING_KEYS — do not reorder.',
    'DEFAULT_WEIGHTS: dict[str, int] = {',
  );
  for (const [k, v] of Object.entries(constants.default_weights)) {
    lines.push(`    ${JSON.stringify(k)}: ${v as number},`);
  }
  lines.push('}', '', '');

  // DEFAULT_FILTERS — dict (snake_case already canonical)
  const df = constants.default_filters;
  lines.push('DEFAULT_FILTERS: dict = {');
  lines.push(`    "min_rent": ${df.min_rent},`);
  lines.push(`    "max_rent": ${df.max_rent},`);
  lines.push(`    "min_commute": ${df.min_commute},`);
  lines.push(`    "max_commute": ${df.max_commute},`);
  lines.push(`    "category_mins": ${j(df.category_mins)},`);
  lines.push(`    "has_live_camera": ${df.has_live_camera ? 'True' : 'False'},`);
  lines.push('}', '', '');

  // DEFAULT_ENVIRONMENT_FILTERS
  const de = constants.default_environment_filters;
  lines.push('DEFAULT_ENVIRONMENT_FILTERS: dict = {');
  lines.push(`    "hide_flood_risk": ${de.hide_flood_risk ? 'True' : 'False'},`);
  lines.push(`    "hide_high_seismic": ${de.hide_high_seismic ? 'True' : 'False'},`);
  lines.push('}', '', '');

  // RENT_FLOOR / RENT_CEILING
  lines.push(
    `RENT_FLOOR = ${constants.rent_floor}`,
    `RENT_CEILING = ${constants.rent_ceiling}`,
    '',
  );

  // RATING_LABELS_EN — dict, order matches RATING_KEYS
  lines.push('# Order matches RATING_KEYS — do not reorder.', 'RATING_LABELS_EN: dict[str, str] = {');
  for (const [k, v] of Object.entries(constants.rating_labels_en)) {
    lines.push(`    ${JSON.stringify(k)}: ${JSON.stringify(v as string)},`);
  }
  lines.push('}', '', '');

  // COMPOSITE_ANCHORS_DEFAULT / PERCENTILE_ANCHORS_EMPTY_FALLBACK
  const cad = constants.composite_anchors_default;
  lines.push(
    'COMPOSITE_ANCHORS_DEFAULT: dict[str, float] = {',
    `    "p5": ${cad.p5},`,
    `    "p50": ${cad.p50},`,
    `    "p95": ${cad.p95},`,
    '}',
    '',
  );
  const paf = constants.percentile_anchors_empty_fallback;
  lines.push(
    'PERCENTILE_ANCHORS_EMPTY_FALLBACK: dict[str, float] = {',
    `    "p5": ${paf.p5},`,
    `    "p50": ${paf.p50},`,
    `    "p95": ${paf.p95},`,
    '}',
    '',
  );

  // PIPELINE_ONLY — module-level namespace
  const po = constants.pipeline_only;
  lines.push(
    '# Constants used only by the offline rating pipeline (compute-ratings.py).',
    '# Format for absolute_caps: dict[category] -> list[(min_rating, threshold)] tuples.',
    '# Not imported by the app or MCP server.',
    'PIPELINE_ONLY = SimpleNamespace(',
    '    absolute_caps={',
  );
  // absolute_caps values: lists of [min_rating, threshold] pairs.
  // Emit as list of tuples so callers can do `(8, 100)`-style unpacking.
  for (const [cat, pairs] of Object.entries(po.absolute_caps)) {
    const pyPairs = (pairs as number[][]).map((p) => `(${p[0]}, ${p[1]})`).join(', ');
    lines.push(`        ${JSON.stringify(cat)}: [${pyPairs}],`);
  }
  lines.push(
    '    },',
    `    tokyo_station_lat=${po.tokyo_station_lat},`,
    `    tokyo_station_lng=${po.tokyo_station_lng},`,
    ')',
    '',
  );

  return lines.join('\n');
}

// ---------- python/city_rating_schema/models.py ----------

/** Map a JSON Schema type → Python type string. Returns null for objects/refs handled by caller. */
function pyType(node: any): string | null {
  if (typeof node !== 'object' || node === null) return 'Any';
  if ('$ref' in node) {
    const refName = node.$ref.replace('#/$defs/', '');
    return pascal(refName);
  }
  if (node.enum) {
    // Literal[...] of strings
    const vals = node.enum.map((v: string) => JSON.stringify(v)).join(', ');
    return `Literal[${vals}]`;
  }
  if (Array.isArray(node.type)) {
    // e.g. ["number", "null"]
    const parts = node.type.map((t: string) => (t === 'null' ? 'None' : pyType({ ...node, type: t })));
    // Deduplicate (None may already be present)
    const unique = Array.from(new Set(parts.filter((p: string) => p !== null)));
    return unique.join(' | ');
  }
  if (node.type === 'number' || node.type === 'integer') return 'float';
  if (node.type === 'string') return 'str';
  if (node.type === 'boolean') return 'bool';
  if (node.type === 'array') {
    const itemT = pyType(node.items) || 'Any';
    return `list[${itemT}]`;
  }
  if (node.type === 'object') {
    // Inline dict with str→number (used by category_mins / preset filters)
    if (node.additionalProperties && typeof node.additionalProperties === 'object') {
      const valT = pyType(node.additionalProperties) || 'Any';
      return `dict[str, ${valT}]`;
    }
    return 'dict';
  }
  return 'Any';
}

function pyFieldName(key: string): { field: string; alias?: string } {
  // The "1k_1ldk" key starts with a digit — not a valid Python identifier.
  // Use an alias: field name is `one_k_1ldk`, alias stays "1k_1ldk".
  // NOTE: "2ldk" also starts with a digit and needs the same treatment.
  if (/^[\d]/.test(key)) {
    // Strip the leading digit(s) + underscore boundary, prefix with `one_`,
    // so "1k_1ldk" → "one_k_1ldk" and "2ldk" → "one_ldk". The alias keeps
    // the original JSON key so wire format round-trips.
    const stripped = key.replace(/^[\d]+_?/, '');
    return { field: `one_${stripped}`, alias: key };
  }
  return { field: key };
}

function emitPydanticModel(name: string, def: any): string {
  const props = def.properties || {};
  const required = new Set<string>(def.required || []);

  // Does any field need an alias (digit-prefixed JSON key)?
  const needsPopulateByName = Object.keys(props).some((k) => /^[\d]/.test(k));

  const out: string[] = [];
  out.push(`class ${pascal(name)}(BaseModel):`);

  // 1. docstring (if any)
  if (def.description) {
    out.push('    """');
    for (const l of String(def.description).split('\n')) out.push(`    ${l}`);
    out.push('    """', '');
  }

  // 2. model_config (if any aliased fields)
  if (needsPopulateByName) {
    out.push('    model_config = ConfigDict(populate_by_name=True)', '');
  }

  // 3. fields
  const fieldLines: string[] = [];
  for (const [key, val] of Object.entries(props)) {
    const isReq = required.has(key);
    const { field, alias } = pyFieldName(key);
    const baseT = pyType(val as any) || 'Any';
    const typeAnn = isReq ? baseT : `Optional[${baseT}]`;
    let rhs: string;
    if (alias) {
      rhs = `Field(..., alias=${JSON.stringify(alias)})`;
    } else if (isReq) {
      rhs = 'Field(...)';
    } else {
      rhs = 'None';
    }
    fieldLines.push(`    ${field}: ${typeAnn} = ${rhs}`);
  }

  if (fieldLines.length === 0) {
    out.push('    pass');
  } else {
    out.push(...fieldLines);
  }
  return out.join('\n');
}

function emitPythonModels(): string {
  const lines: string[] = [HEADER_PY];

  lines.push(
    'from __future__ import annotations',
    '',
    'from typing import Literal, Optional',
    '',
    'from pydantic import BaseModel, ConfigDict, Field',
    '',
  );

  // Enum types — emit as Literal aliases (one line each).
  const enumDefs = Object.entries(defs).filter(([, d]) => d.enum);
  for (const [name, def] of enumDefs) {
    const vals = (def as any).enum.map((v: string) => JSON.stringify(v)).join(', ');
    lines.push(`${pascal(name)} = Literal[${vals}]`);
  }
  if (enumDefs.length > 0) lines.push('');

  // Object models in $def order. Use forward refs if needed.
  const objDefs = Object.entries(defs).filter(([, d]) => d.type === 'object');
  for (const [name, def] of objDefs) {
    lines.push(emitPydanticModel(name, def), '');
  }

  return lines.join('\n');
}

// ---------- python/city_rating_schema/__init__.py ----------

function emitPythonInit(): string {
  const enumNames = Object.entries(defs)
    .filter(([, d]) => d.enum)
    .map(([n]) => pascal(n));
  const objNames = Object.entries(defs)
    .filter(([, d]) => d.type === 'object')
    .map(([n]) => pascal(n));
  return [
    HEADER_PY,
    'from .constants import (',
    '    RATING_KEYS,',
    '    LEGACY_WEIGHT_KEYS,',
    '    DEFAULT_WEIGHTS,',
    '    DEFAULT_FILTERS,',
    '    DEFAULT_ENVIRONMENT_FILTERS,',
    '    RENT_FLOOR,',
    '    RENT_CEILING,',
    '    RATING_LABELS_EN,',
    '    COMPOSITE_ANCHORS_DEFAULT,',
    '    PERCENTILE_ANCHORS_EMPTY_FALLBACK,',
    '    PIPELINE_ONLY,',
    ')',
    'from .models import (',
    ...[...enumNames, ...objNames].map((n) => `    ${n},`),
    ')',
    '',
    `__all__ = [`,
    '    "RATING_KEYS",',
    '    "LEGACY_WEIGHT_KEYS",',
    '    "DEFAULT_WEIGHTS",',
    '    "DEFAULT_FILTERS",',
    '    "DEFAULT_ENVIRONMENT_FILTERS",',
    '    "RENT_FLOOR",',
    '    "RENT_CEILING",',
    '    "RATING_LABELS_EN",',
    '    "COMPOSITE_ANCHORS_DEFAULT",',
    '    "PERCENTILE_ANCHORS_EMPTY_FALLBACK",',
    '    "PIPELINE_ONLY",',
    ...[...enumNames, ...objNames].map((n) => `    "${n}",`),
    ']',
    '',
  ].join('\n');
}

// ---------- main ----------

emit(join(PKG_ROOT, 'ts', 'constants.ts'), emitTsConstants());
emit(join(PKG_ROOT, 'ts', 'types.ts'), emitTsTypes());
emit(join(PKG_ROOT, 'ts', 'index.ts'), emitTsIndex());
emit(join(PKG_ROOT, 'python', 'city_rating_schema', 'constants.py'), emitPythonConstants());
emit(join(PKG_ROOT, 'python', 'city_rating_schema', 'models.py'), emitPythonModels());
emit(join(PKG_ROOT, 'python', 'city_rating_schema', '__init__.py'), emitPythonInit());

console.log('Generated: ts/constants.ts, ts/types.ts, ts/index.ts, python/city_rating_schema/{__init__,constants,models}.py');
